version: 0.2 

env:
  variables:
    CHECKMARX_BUGTRACKER: "None" # or JIRA
    #ADDITIONAL_PARAMS: "--namespace=$GH_REPO_OWNER --repo-name=$GH_REPO_NAME --branch=$GH_BRANCH"
    #ADDITIONAL_PARAMS: "--config=cx.config --checkmarx.settings-override=true --jira.url=$JIRA_URL --jira.username=$JIRA_USER --jira.token=$JIRA_TOKEN"
phases: 
  pre_build: 
    commands: 
       - export CX_REPO_NAME=$(basename "$CODEBUILD_SOURCE_REPO_URL" .git)
       - export CX_REPO_BRANCH=$(basename "$CODEBUILD_WEBHOOK_HEAD_REF") 
       - export CX_PROJECT_NAME=$(echo "$CODEBUILD_BUILD_ID" | cut -f1 -d:)
       - env
       - |
         java -jar /app/cx-flow.jar \
           --scan \
           --cx-project="$CX_REPO_NAME"-"$CX_REPO_BRANCH" \
           --app="$CX_REPO_NAME" \
           --branch="$CX_REPO_BRANCH" \
           --repo-name="$CX_REPO_NAME" \
           --namespace="$CX_REPO_NAME" \
           --f=. \
           --cx-flow.enabled-vulnerability-scanners="$CHECKMARX_SCANNERS"  \
           --checkmarx.version="9.0" \
           --checkmarx.base-url="$CHECKMARX_SERVER" \
           --checkmarx.client-secret="$CHECKMARX_CLIENT_SECRET" \
           --checkmarx.username="$CHECKMARX_USERNAME" \
           --checkmarx.password="$CHECKMARX_PASSWORD" \
           --checkmarx.client-id="$CHECKMARX_CLIENT_ID" \
           --cx-team="$CHECKMARX_TEAM" \
           --checkmarx.preset="$CHECKMARX_PRESET" \
           --checkmarx.scope="$CHECKMARX_SCOPE" \
           --checkmarx.configuration="$CHECKMARX_CONFIGURATION" \
           --cx-flow.bug-tracker="$CHECKMARX_BUGTRACKER" \
           --cx-flow.bug-tracker-impl="$CHECKMARX_BUGTRACKER" \
           --cx-flow.filter-severity="$CHECKMARX_FILTER_SEVERITIES" \
           --cx-flow.filter-state="$CHECKMARX_FILTER_STATE" \
           --checkmarx.exclude-folders="$CHECKMARX_EXCLUDE_FOLDERS" \
           --checkmarx.exclude-files="$CHECKMARX_EXCLUDE_FILES" \
           "$ADDITIONAL_PARAMS"

